#!/bin/sh

case "${1}" in
  hibernate|suspend)
    # /etc/init.d/mythtv-backend stop
    stop mythtv-backend
        ;;
  resume|thaw)
    # /etc/init.d/mythtv-backend start
    start mythtv-backend
        ;;
  *)
    ;;
esac
