#!/usr/bin/python
import MythTV, sys

try:
    backend = MythTV.MythBE()
except MythTV.MythBEError:
    sys.exit(1)

allRecorders = backend.getRecorderList()
freeRecorders = backend.getFreeRecorderList()

if set(allRecorders) == set(freeRecorders):
    print("not recording")
else:
    print("recording")





