#!/usr/bin/python
import MythTV, sys

try:
    backend = MythTV.MythBE()
except MythTV.MythBEError:
    sys.exit(1)

recorders = backend.getRecorderList()

for recorder in recorders:
    if backend.isRecording(recorder):
        print("recording")
        exit()

print ("not recording")
